/**
 * The single core entity of Escoffe.
 *
 * An Ingredient is one item tracked in the pantry. The whole app is a
 * collection of these, persisted as a plain array via @tauri-apps/plugin-store.
 */
export interface Ingredient {
  /** Stable unique identifier (UUID v4). */
  id: string;
  /** Human-readable name, e.g. "Olive oil". */
  name: string;
  /** Optional free-form amount, e.g. "500 g" or "2 cans". */
  quantity?: string;
  /** Expiration date as an ISO date string (YYYY-MM-DD). */
  expirationDate: string;
  /** Optional free-form notes. */
  notes?: string;
}

/** Shape used by the form when creating/editing (id is generated by the store). */
export type IngredientDraft = Omit<Ingredient, "id">;
